FROM bitnami/mongodb:latest

# WORKDIR /usr/src/app

EXPOSE 27017/tcp

EXPOSE 27017/udp

RUN mongod -v

# RUN mongo

# RUN use FOOTBALL_PLAYERS

# RUN db.players.insert({name: "Mihail", secondName: "Giant", team: "teamless", birthday: "10.05.1995", online: true})
